// Code generated by taurus_go/entity, DO NOT EDIT.

package blog

import "github.com/yohobala/taurus_go/entity/entitysql"

type OrderOption func(*entitysql.Order)

func ByPrimary(o *entitysql.Order) {
	(&ByID{}).Apply(o)
}

type OrderTerm interface {
	Apply(*entitysql.Order)
}

type ByID struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByID) Apply(o *entitysql.Order) {
	o.SetColumn(FieldID.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByID) Desc() *ByID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByID) Asc() *ByID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByID) NullsFirst() *ByID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByID) NullsLast() *ByID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByUUID struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByUUID) Apply(o *entitysql.Order) {
	o.SetColumn(FieldUUID.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByUUID) Desc() *ByUUID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByUUID) Asc() *ByUUID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByUUID) NullsFirst() *ByUUID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByUUID) NullsLast() *ByUUID {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByDescription struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByDescription) Apply(o *entitysql.Order) {
	o.SetColumn(FieldDescription.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByDescription) Desc() *ByDescription {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByDescription) Asc() *ByDescription {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByDescription) NullsFirst() *ByDescription {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByDescription) NullsLast() *ByDescription {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}

type ByCreatedTime struct {
	OrderTerm
	Options []OrderOption
	Field   string
}

func (b *ByCreatedTime) Apply(o *entitysql.Order) {
	o.SetColumn(FieldCreatedTime.Name.String())
	if len(b.Options) == 0 {
		b.Asc()
	}
	for _, opt := range b.Options {
		opt(o)
	}
}

func (b *ByCreatedTime) Desc() *ByCreatedTime {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Desc()
	})
	return b
}

func (b *ByCreatedTime) Asc() *ByCreatedTime {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.Asc()
	})
	return b
}

func (b *ByCreatedTime) NullsFirst() *ByCreatedTime {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsFirst()
	})
	return b
}

func (b *ByCreatedTime) NullsLast() *ByCreatedTime {
	b.Options = append(b.Options, func(o *entitysql.Order) {
		o.NullsLast()
	})
	return b
}
