// Code generated by taurus_go, DO NOT EDIT.

package blog

import (
	"context"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

// BlogEntityQuery is the query action for the BlogEntity.
type BlogEntityQuery struct {
	config     *BlogEntityConfig
	ctx        *entitysql.QueryContext
	predicates []func(*entitysql.Predicate)
}

// NewBlogEntityQuery creates a new BlogEntityQuery.
func NewBlogEntityQuery(c *internal.Config, t entity.Tracker, ms *mutations) *BlogEntityQuery {
	return &BlogEntityQuery{
		config: &BlogEntityConfig{
			Config:    c,
			mutations: ms,
		},
		ctx: &entitysql.QueryContext{},
	}
}

func (o *BlogEntityQuery) Where(predicates ...func(*entitysql.Predicate)) *BlogEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *BlogEntityQuery) Limit(limit int) *BlogEntityQuery {
	o.ctx.Limit = &limit
	return o
}

// First returns the first result of the query.
func (o *BlogEntityQuery) First(ctx context.Context) (*BlogEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// ToList returns the list of results of the query.
func (o *BlogEntityQuery) ToList(ctx context.Context) ([]*BlogEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *BlogEntityQuery) Single(ctx context.Context) (*BlogEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *BlogEntityQuery) sqlSingle(ctx context.Context) (*BlogEntity, error) {
	var (
		spec = o.querySpec()
		res  = New(o.config.Config, o.config.mutations)
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.FieldName) error {
		return scan(res, fields, rows)
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if err := res.setUnchanged(); err != nil {
		return nil, err
	}
	return res, nil
}

func (o *BlogEntityQuery) sqlAll(ctx context.Context) ([]*BlogEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*BlogEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.FieldName) error {
		e := New(o.config.Config, o.config.mutations)
		if err := scan(e, fields, rows); err != nil {
			return err
		} else {
			res = append(res, e)
			return nil
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	return res, nil
}

func (o *BlogEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(Entity, columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s.Entity.Columns = make([]entitysql.FieldName, 0, len(fields))
		s.Entity.Columns = append(s.Entity.Columns, fields...)
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	return s
}
