// Code generated by taurus_go/entity, DO NOT EDIT.

package blog

import (
	"time"

	"github.com/yohobala/taurus_go/entity/entitysql"
)

type PredID struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredID) EQ(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredID) NEQ(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredID) GT(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredID) GTE(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredID) LT(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredID) LTE(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredID) In(ids ...int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		p.In(FieldID.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredID) NotIn(ids ...int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		p.NotIn(FieldID.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredID) Like(id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

type PredUUID struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredUUID) EQ(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredUUID) NEQ(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredUUID) GT(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredUUID) GTE(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredUUID) LT(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredUUID) LTE(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredUUID) In(uuids ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(uuids))
		for i := range v {
			v[i] = uuids[i]
		}
		p.In(FieldUUID.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredUUID) NotIn(uuids ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(uuids))
		for i := range v {
			v[i] = uuids[i]
		}
		p.NotIn(FieldUUID.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredUUID) Like(uuid string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldUUID.Name.String(), p.Builder.FindAs(Entity), uuid)
	}
}

type PredDescription struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredDescription) EQ(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredDescription) NEQ(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredDescription) GT(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredDescription) GTE(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredDescription) LT(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredDescription) LTE(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredDescription) In(descriptions ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(descriptions))
		for i := range v {
			v[i] = descriptions[i]
		}
		p.In(FieldDescription.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredDescription) NotIn(descriptions ...string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(descriptions))
		for i := range v {
			v[i] = descriptions[i]
		}
		p.NotIn(FieldDescription.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredDescription) Like(description string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldDescription.Name.String(), p.Builder.FindAs(Entity), description)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredDescription) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldDescription.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredDescription) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldDescription.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredCreatedTime struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredCreatedTime) EQ(created_time time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredCreatedTime) NEQ(created_time time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredCreatedTime) GT(created_time time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredCreatedTime) GTE(created_time time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredCreatedTime) LT(created_time time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredCreatedTime) LTE(created_time time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredCreatedTime) In(created_times ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(created_times))
		for i := range v {
			v[i] = created_times[i]
		}
		p.In(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredCreatedTime) NotIn(created_times ...time.Time) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(created_times))
		for i := range v {
			v[i] = created_times[i]
		}
		p.NotIn(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredCreatedTime) Like(created_time string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity), created_time)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredCreatedTime) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredCreatedTime) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldCreatedTime.Name.String(), p.Builder.FindAs(Entity))
	}
}
