// Code generated by taurus_go, DO NOT EDIT.

package entity

import (
	"taurus_go_demo/entity/new/entity/author"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/field"
)

// authorID is ID field
type authorID struct {
	field.IntStorage[int64]
	config *authorEntityConfig
}

// newauthorID creates a new authorID
func newAuthorID(c *authorEntityConfig) *authorID {
	t := &authorID{}
	t.config = c
	return t
}

// Set sets the value of ID field
func (t *authorID) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged {
		t.config.authorEntityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(author.FieldID.Name.String())
	}
}

// Get gets the value of ID field
func (t *authorID) Get() *int64 {
	return t.IntStorage.Get()
}

// authorName is Name field
type authorName struct {
	field.StringStorage
	config *authorEntityConfig
}

// newauthorName creates a new authorName
func newAuthorName(c *authorEntityConfig) *authorName {
	t := &authorName{}
	t.config = c
	return t
}

// Set sets the value of Name field
func (t *authorName) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged {
		t.config.authorEntityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(author.FieldName.Name.String())
	}
}

// Get gets the value of Name field
func (t *authorName) Get() *string {
	return t.StringStorage.Get()
}
