// Code generated by taurus_go, DO NOT EDIT.

package entity

import (
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity/entitysql"
)

type AuthorEntityRelation struct {
	PostEntityRel
	Config   internal.EntityConfig
	relation entitysql.RelationDesc
	children []Rel
}

func NewAuthorEntityRelation(config internal.EntityConfig, desc entitysql.RelationDesc) *AuthorEntityRelation {
	return &AuthorEntityRelation{
		Config:   config,
		relation: desc,
		children: []Rel{},
	}
}

func (r *AuthorEntityRelation) Where(predicates ...entitysql.PredicateFunc) *AuthorEntityRelation {
	r.relation.Predicates = append(r.relation.Predicates, predicates...)
	return r
}

func (r *AuthorEntityRelation) Include(rels ...AuthorEntityRel) *AuthorEntityRelation {
	// Create a slice of type Rel with the same length as r.children
	newRels := make([]Rel, len(rels))
	for i, r := range rels {
		// Convert each AuthorEntityRel to Rel and store it in the new slice
		newRels[i] = Rel(r)
	}
	r.children = append(r.children, newRels...)
	return r
}

func (r *AuthorEntityRelation) Desc() (entitysql.RelationDesc, []Rel, internal.EntityConfig) {
	return r.relation, r.children, r.Config
}

func (r *AuthorEntityRelation) reset() {
	for _, child := range r.children {
		child.reset()
	}
	r.relation.Reset()
	r.children = []Rel{}
}
