// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"fmt"
	"taurus_go_demo/entity/new/entity/author"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

type AuthorEntity struct {
	internal.Entity
	config *authorEntityConfig

	// ID Author primary key
	ID *authorID

	Name *authorName

	Posts []*PostEntity
}

// authorEntityConfig holds the configuration for the AuthorEntity.
type authorEntityConfig struct {
	internal.EntityConfig
	*internal.Dialect
	*entity.Mutation
	*authorEntityMutations
	name string
}

func newAuthorEntityConfig(c *internal.Dialect) *authorEntityConfig {
	return &authorEntityConfig{
		Dialect:               c,
		authorEntityMutations: newAuthorEntityMutations(),
		name:                  "author",
	}
}

// New creates a new AuthorEntity, but does not add tracking.
func (c *authorEntityConfig) New() internal.Entity {
	b := entity.NewMutation(entity.Detached)
	e := &AuthorEntity{
		config: &authorEntityConfig{
			Mutation:              b,
			Dialect:               c.Dialect,
			authorEntityMutations: c.authorEntityMutations,
		},
	}
	e.setState(entity.Detached)
	e.ID = newAuthorID(e.config)
	e.Name = newAuthorName(e.config)
	return e
}

func (c *authorEntityConfig) Desc() internal.EntityConfigDesc {
	return internal.EntityConfigDesc{
		Name: c.name,
	}
}

// String implements the fmt.Stringer interface.
func (e *AuthorEntity) String() string {
	return fmt.Sprintf("{ ID: %v, Name: %v, Posts: %v}",
		e.ID,
		e.Name,
		e.Posts,
	)
}

// State returns the state of the AuthorEntity.
func (e *AuthorEntity) State() entity.EntityState {
	return e.config.State()
}

// remove removes the AuthorEntity from the database.
func (e *AuthorEntity) remove() error {
	return e.setState(entity.Deleted)
}

// create creates a new AuthorEntity and adds tracking.
func (e *AuthorEntity) create(name string, options ...func(*AuthorEntity)) (*AuthorEntity, error) {
	e.setState(entity.Added)
	e.Name.Set(name)
	for _, option := range options {
		option(e)
	}
	return e, nil
}

// setUnchanged sets the state of the AuthorEntity to unchanged.
func (e *AuthorEntity) setUnchanged() error {
	return e.setState(entity.Unchanged)
}

// setState sets the state of the AuthorEntity.
func (e *AuthorEntity) setState(state entity.EntityState) error {
	return e.config.authorEntityMutations.SetEntityState(e, state)
}

// scan scans the database for the AuthorEntity.
func (e *AuthorEntity) scan(fields []entitysql.ScannerField) []any {
	if len(fields) == 0 {
		args := make([]any, len(author.Columns))
		for i, c := range author.Columns {
			switch c.String() {
			case author.FieldID.Name.String():
				v := e.ID
				v.Set(*new(int64))
				args[i] = v
			case author.FieldName.Name.String():
				v := e.Name
				v.Set(*new(string))
				args[i] = v
			}
		}
		return args
	} else {
		args := make([]any, len(fields))
		for i := range fields {
			switch fields[i].String() {
			case author.FieldID.Name.String():
				v := e.ID
				v.Set(*new(int64))
				args[i] = v
			case author.FieldName.Name.String():
				v := e.Name
				v.Set(*new(string))
				args[i] = v
			}
		}
		return args
	}
}

func (e *AuthorEntity) createRel(buidler *entitysql.ScannerBuilder, scanner *internal.QueryScanner) {
	switch scanner.Config.Desc().Name {
	case "post":
		postEntity := scanner.Config.New().(*PostEntity)
		buidler.Append(scanner.TableNum-1, postEntity.scan([]entitysql.ScannerField{})...)
		e.Posts = append(e.Posts, postEntity)
		for _, c := range scanner.Children {
			postEntity.createRel(buidler, c)
		}
	}
}

func mergeAuthorEntity(es []*AuthorEntity, e *AuthorEntity) []*AuthorEntity {
	if e == nil {
		return es
	}
	if len(es) == 0 {
		es = append(es, e)
	} else {
		v := es[len(es)-1]

		if e.ID.Get() != nil {
			if v.ID.Get() != nil && *v.ID.Get() == *e.ID.Get() {
				for _, post := range e.Posts {
					posts := mergePostEntity(v.Posts, post)
					if len(posts) > 0 {
						v.Posts = posts
					}
				}
			} else {
				es = append(es, e)
			}
		}
	}
	return es
}
