// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"taurus_go_demo/entity/new/entity/blog"
	"time"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/field"
)

// blogID is ID field
type blogID struct {
	field.IntStorage[int64]
	config *blogEntityConfig
}

// newblogID creates a new blogID
func newBlogID(c *blogEntityConfig) *blogID {
	t := &blogID{}
	t.config = c
	return t
}

// Set sets the value of ID field
func (t *blogID) Set(v int64) {
	t.IntStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.blogEntityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(blog.FieldID.Name.String())
	}
}

// Get gets the value of ID field
func (t *blogID) Get() *int64 {
	return t.IntStorage.Get()
}

// blogUUID is UUID field
type blogUUID struct {
	field.StringStorage[string]
	config *blogEntityConfig
}

// newblogUUID creates a new blogUUID
func newBlogUUID(c *blogEntityConfig) *blogUUID {
	t := &blogUUID{}
	t.config = c
	return t
}

// Set sets the value of UUID field
func (t *blogUUID) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.blogEntityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(blog.FieldUUID.Name.String())
	}
}

// Get gets the value of UUID field
func (t *blogUUID) Get() *string {
	return t.StringStorage.Get()
}

// blogDesc is Desc field
type blogDesc struct {
	field.StringStorage[string]
	config *blogEntityConfig
}

// newblogDesc creates a new blogDesc
func newBlogDesc(c *blogEntityConfig) *blogDesc {
	t := &blogDesc{}
	t.config = c
	return t
}

// Set sets the value of Desc field
func (t *blogDesc) Set(v string) {
	t.StringStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.blogEntityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(blog.FieldDesc.Name.String())
	}
}

// Get gets the value of Desc field
func (t *blogDesc) Get() *string {
	return t.StringStorage.Get()
}

// blogCreatedTime is CreatedTime field
type blogCreatedTime struct {
	field.TimestampStorage[time.Time]
	config *blogEntityConfig
}

// newblogCreatedTime creates a new blogCreatedTime
func newBlogCreatedTime(c *blogEntityConfig) *blogCreatedTime {
	t := &blogCreatedTime{}
	t.config = c
	return t
}

// Set sets the value of CreatedTime field
func (t *blogCreatedTime) Set(v time.Time) {
	t.TimestampStorage.Set(v)
	if t.config.State() == entity.Unchanged || t.config.State() == entity.Modified {
		t.config.blogEntityMutations.ChangeEntityState(t.config.Mutation, entity.Modified)
		t.config.Mutation.SetFields(blog.FieldCreatedTime.Name.String())
	}
}

// Get gets the value of CreatedTime field
func (t *blogCreatedTime) Get() *time.Time {
	return t.TimestampStorage.Get()
}
