// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/blog"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

// blogEntityUpdate is the update action for the blogEntity.
type blogEntityUpdate struct {
	config     *internal.Dialect
	ctx        *entitysql.QueryContext
	tracker    entity.Tracker
	es         []*BlogEntity
	predicates [][]entitysql.PredicateFunc
	sets       []map[string]entitysql.CaseSpec
	total      int
	batchIndex []int
}

// newBlogEntityUpdate creates a new blogEntityUpdate.
func newBlogEntityUpdate(c *internal.Dialect, es ...*BlogEntity) *blogEntityUpdate {
	return &blogEntityUpdate{
		config:     c,
		ctx:        &entitysql.QueryContext{},
		es:         es,
		predicates: [][]entitysql.PredicateFunc{},
		batchIndex: []int{0},
	}
}

func (o *blogEntityUpdate) update(ctx context.Context, tx dialect.Tx) error {
	return o.sqlUpdate(ctx, tx)
}

func (o *blogEntityUpdate) sqlUpdate(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.updateSpec()
		res       = o.es
		cursor    = 0
	)
	if err != nil {
		return err
	}
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := res[cursor]
		cursor++
		args := e.scan(fields)
		if err := rows.Scan(args...); err != nil {
			return err
		} else {
			res = append(res, e)
			return e.setUnchanged()
		}
	}
	return entitysql.NewUpdate(ctx, tx, spec)
}

func (o *blogEntityUpdate) updateSpec() (*entitysql.UpdateSpec, error) {
	spec := entitysql.NewUpdateSpec(blog.Entity, blog.Columns)
	if len(o.predicates) != len(o.sets) {
		return nil, entity.Err_0100030005
	}
	if err := o.setEntity(spec); err != nil {
		return nil, err
	}
	o.mergeArgs(spec)
	return spec, nil
}

// setEntity 用于在updateSpec中设置[]*blogEntity的配置，
// 一般来说这个setEntity里的entity都是通过状态追踪，自动添加的。
func (o *blogEntityUpdate) setEntity(spec *entitysql.UpdateSpec) error {
	predID := &blog.PredID{}
	num := 0
	for i, e := range o.es {
		fields := e.config.Mutation.Fields()
		if len(fields) == 0 {
			return entity.Err_0100030002.Sprintf(e.config.Tag)
		}
		o.predicates = append(o.predicates, []entitysql.PredicateFunc{})
		o.sets = append(o.sets, map[string]entitysql.CaseSpec{})
		// 因为判断过predicates和set长度，所以这里默认等长
		index := len(o.predicates) - 1
		if i > 0 {
			o.predicates[index] = append(o.predicates[index], entitysql.Or, predID.EQ(*e.ID.Get()))
		} else {
			o.predicates[index] = append(o.predicates[index], predID.EQ(*e.ID.Get()))
		}
		num++
		for _, f := range fields {
			switch f {
			case blog.FieldID.Name.String():
				v, err := e.ID.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(blog.FieldID.Name)
				fieldSpace.Param = v
				fieldSpace.Format = e.ID.SqlFormatParam()
				o.sets[index][blog.FieldID.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predID.EQ(*e.ID.Get()),
				}
				num++
			case blog.FieldUUID.Name.String():
				v, err := e.UUID.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(blog.FieldUUID.Name)
				fieldSpace.Param = v
				fieldSpace.Format = e.UUID.SqlFormatParam()
				o.sets[index][blog.FieldUUID.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predID.EQ(*e.ID.Get()),
				}
				num++
			case blog.FieldDesc.Name.String():
				v, err := e.Desc.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(blog.FieldDesc.Name)
				fieldSpace.Param = v
				fieldSpace.Format = e.Desc.SqlFormatParam()
				o.sets[index][blog.FieldDesc.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predID.EQ(*e.ID.Get()),
				}
				num++
			case blog.FieldCreatedTime.Name.String():
				v, err := e.CreatedTime.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return err
				}
				fieldSpace := entitysql.NewFieldSpec(blog.FieldCreatedTime.Name)
				fieldSpace.Param = v
				fieldSpace.Format = e.CreatedTime.SqlFormatParam()
				o.sets[index][blog.FieldCreatedTime.Name.String()] = entitysql.CaseSpec{
					Field: fieldSpace,
					When:  predID.EQ(*e.ID.Get()),
				}
				num++
			}
		}
		batchSize := *(entity.GetConfig().BatchSize)
		if (o.total+num)/batchSize > len(o.batchIndex) {
			o.batchIndex = append(o.batchIndex, len(o.predicates))
		} else {
			o.batchIndex[len(o.batchIndex)-1] = len(o.predicates)
		}
		o.total += num
	}
	return nil
}

func (o *blogEntityUpdate) mergeArgs(spec *entitysql.UpdateSpec) {
	for i, end := range o.batchIndex {
		var begin int
		if i == 0 {
			begin = 0
		} else {
			begin = o.batchIndex[i-1]
		}
		pred := []entitysql.PredicateFunc{}
		set := map[string][]entitysql.CaseSpec{}
		for _, ps := range o.predicates[begin:end] {
			pred = append(pred, ps...)
		}
		for _, ss := range o.sets[begin:end] {
			for k, v := range ss {
				set[k] = append(set[k], v)
			}
		}
		spec.Predicate = append(spec.Predicate, func(p *entitysql.Predicate) {
			for _, f := range pred {
				f(p)
			}
		})
		spec.Sets = append(spec.Sets, set)
	}
}
