// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/blog"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

// blogEntityQuery is the query action for the blogEntity.
type blogEntityQuery struct {
	config       *blogEntityConfig
	ctx          *entitysql.QueryContext
	predicates   []entitysql.PredicateFunc
	rels         []blogEntityRel
	order        []blog.OrderTerm
	scanner      []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *blogEntityQuery) First(ctx context.Context) (*BlogEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// newBlogEntityQuery creates a new blogEntityQuery.
func newBlogEntityQuery(c *internal.Dialect, t entity.Tracker, ms *blogEntityMutations) *blogEntityQuery {
	return &blogEntityQuery{
		config: &blogEntityConfig{
			Dialect:             c,
			blogEntityMutations: ms,
		},
		ctx:          &entitysql.QueryContext{},
		predicates:   []entitysql.PredicateFunc{},
		rels:         []blogEntityRel{},
		order:        []blog.OrderTerm{},
		scanner:      []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}

func (o *blogEntityQuery) Where(predicates ...entitysql.PredicateFunc) *blogEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *blogEntityQuery) Limit(limit int) *blogEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (o *blogEntityQuery) Order(term ...blog.OrderTerm) *blogEntityQuery {
	o.order = append(o.order, term...)
	return o
}

func (o *blogEntityQuery) Include(rels ...blogEntityRel) *blogEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *blogEntityQuery) ToList(ctx context.Context) ([]*BlogEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *blogEntityQuery) Single(ctx context.Context) (*BlogEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *blogEntityQuery) sqlSingle(ctx context.Context) (*BlogEntity, error) {
	var (
		spec = o.querySpec()
		res  *BlogEntity
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *BlogEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan(fields)...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}
			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = e
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if res != nil {
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		r.reset()
	}
	return res, nil
}

func (o *blogEntityQuery) sqlAll(ctx context.Context) ([]*BlogEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*BlogEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *BlogEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergeBlogEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *blogEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(blog.Entity, blog.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s = entitysql.NewQuerySpec(blog.Entity, fields)
	}
	for i := range s.Entity.Columns {
		switch blog.Columns[i] {
		case blog.FieldID.Name:
			var a *blogID = new(blogID)
			fieldSpace := entitysql.NewFieldSpec(blog.FieldID.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case blog.FieldUUID.Name:
			var a *blogUUID = new(blogUUID)
			fieldSpace := entitysql.NewFieldSpec(blog.FieldUUID.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case blog.FieldDesc.Name:
			var a *blogDesc = new(blogDesc)
			fieldSpace := entitysql.NewFieldSpec(blog.FieldDesc.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case blog.FieldCreatedTime.Name:
			var a *blogCreatedTime = new(blogCreatedTime)
			fieldSpace := entitysql.NewFieldSpec(blog.FieldCreatedTime.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		}
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, blog.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func(s *entitysql.Selector) {
				o.scanner = o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func(order *entitysql.Order) {
			o.Apply(order)
		})
	}
	return s
}

func (o *blogEntityQuery) addRels(s *entitysql.Selector, t *entitysql.SelectTable, rel rel, scanner []*internal.QueryScanner) []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tableNum := join.GetAs()
	qs := internal.QueryScanner{Config: config, Children: []*internal.QueryScanner{}, TableNum: tableNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}
