// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/field_demo"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/zodileap/taurus_go/entity"
	"github.com/zodileap/taurus_go/entity/dialect"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

// FieldDemoEntityQuery is the query action for the FieldDemoEntity.
type FieldDemoEntityQuery struct {
	config       *fielddemoentityConfig
	ctx          *entitysql.QueryContext
	predicates   []entitysql.PredicateFunc
	rels         []fielddemoentityRel
	order        []field_demo.OrderTerm
	scanner      []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *FieldDemoEntityQuery) First(ctx context.Context) (*FieldDemoEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// newFieldDemoEntityQuery creates a new FieldDemoEntityQuery.
func newFieldDemoEntityQuery(c *internal.Dialect, t entity.Tracker, ms *fielddemoentityMutations) *FieldDemoEntityQuery {
	return &FieldDemoEntityQuery{
		config: &fielddemoentityConfig{
			Dialect:                  c,
			fielddemoentityMutations: ms,
		},
		ctx:          &entitysql.QueryContext{},
		predicates:   []entitysql.PredicateFunc{},
		rels:         []fielddemoentityRel{},
		order:        []field_demo.OrderTerm{},
		scanner:      []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}

func (o *FieldDemoEntityQuery) Where(predicates ...entitysql.PredicateFunc) *FieldDemoEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *FieldDemoEntityQuery) Limit(limit int) *FieldDemoEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (o *FieldDemoEntityQuery) Order(term ...field_demo.OrderTerm) *FieldDemoEntityQuery {
	o.order = append(o.order, term...)
	return o
}

func (o *FieldDemoEntityQuery) Include(rels ...fielddemoentityRel) *FieldDemoEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *FieldDemoEntityQuery) ToList(ctx context.Context) ([]*FieldDemoEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *FieldDemoEntityQuery) Single(ctx context.Context) (*FieldDemoEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *FieldDemoEntityQuery) sqlSingle(ctx context.Context) (*FieldDemoEntity, error) {
	var (
		spec = o.querySpec()
		res  *FieldDemoEntity
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *FieldDemoEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan(fields)...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}
			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = e
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if res != nil {
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		r.reset()
	}
	return res, nil
}

func (o *FieldDemoEntityQuery) sqlAll(ctx context.Context) ([]*FieldDemoEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*FieldDemoEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *FieldDemoEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergeFieldDemoEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *FieldDemoEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(field_demo.Entity, field_demo.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s = entitysql.NewQuerySpec(field_demo.Entity, fields)
	}
	for i := range s.Entity.Columns {
		switch field_demo.Columns[i] {
		case field_demo.FieldInt64F.Name:
			var a *fieldDemo_Int64F = new(fieldDemo_Int64F)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldInt64F.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldVarF.Name:
			var a *fieldDemo_VarF = new(fieldDemo_VarF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldVarF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldBoolF.Name:
			var a *fieldDemo_BoolF = new(fieldDemo_BoolF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldBoolF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldIntArrayF.Name:
			var a *fieldDemo_IntArrayF = new(fieldDemo_IntArrayF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldIntArrayF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldIntarray2F.Name:
			var a *fieldDemo_Intarray2F = new(fieldDemo_Intarray2F)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldIntarray2F.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldStringArrayF.Name:
			var a *fieldDemo_StringArrayF = new(fieldDemo_StringArrayF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldStringArrayF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldBoolArrayF.Name:
			var a *fieldDemo_BoolArrayF = new(fieldDemo_BoolArrayF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldBoolArrayF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldTimeF.Name:
			var a *fieldDemo_TimeF = new(fieldDemo_TimeF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldTimeF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case field_demo.FieldTimeArrayF.Name:
			var a *fieldDemo_TimeArrayF = new(fieldDemo_TimeArrayF)
			fieldSpace := entitysql.NewFieldSpec(field_demo.FieldTimeArrayF.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		}
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, field_demo.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func(s *entitysql.Selector) {
				o.scanner = o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func(order *entitysql.Order) {
			o.Apply(order)
		})
	}
	return s
}

func (o *FieldDemoEntityQuery) addRels(s *entitysql.Selector, t *entitysql.SelectTable, rel rel, scanner []*internal.QueryScanner) []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tableNum := join.GetAs()
	qs := internal.QueryScanner{Config: config, Children: []*internal.QueryScanner{}, TableNum: tableNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}
