// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/zodileap/taurus_go/entity/entitysql"
)

type fielddemoentityRelation struct {
	Config   internal.EntityConfig
	relation entitysql.RelationDesc
	children []rel
}

func newFielddemoentityRelation(config internal.EntityConfig, desc entitysql.RelationDesc) *fielddemoentityRelation {
	return &fielddemoentityRelation{
		Config:   config,
		relation: desc,
		children: []rel{},
	}
}

func (r *fielddemoentityRelation) Where(predicates ...entitysql.PredicateFunc) *fielddemoentityRelation {
	r.relation.Predicates = append(r.relation.Predicates, predicates...)
	return r
}

func (r *fielddemoentityRelation) Include(rels ...fielddemoentityRel) *fielddemoentityRelation {
	// Create a slice of type Rel with the same length as r.children
	newRels := make([]rel, len(rels))
	for i, r := range rels {
		// Convert each fielddemoentityRel to Rel and store it in the new slice
		newRels[i] = rel(r)
	}
	r.children = append(r.children, newRels...)
	return r
}

func (r *fielddemoentityRelation) Desc() (entitysql.RelationDesc, []rel, internal.EntityConfig) {
	return r.relation, r.children, r.Config
}

func (r *fielddemoentityRelation) reset() {
	for _, child := range r.children {
		child.reset()
	}
	r.relation.Reset()
	r.children = []rel{}
}
