// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/geo_demo"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

// geoEntityCreate is the create action for the geoEntity.
type geoEntityCreate struct {
	config *internal.Dialect
	es     []*GeoEntity
}

// newGeoEntityCreate creates a new geoEntityCreate.
func newGeoEntityCreate(c *internal.Dialect, es ...*GeoEntity) *geoEntityCreate {
	return &geoEntityCreate{
		config: c,
		es:     es,
	}
}

// create executes the create action.
func (o *geoEntityCreate) create(ctx context.Context, tx dialect.Tx) error {
	return o.sqlCreate(ctx, tx)
}

// sqlCreate executes the SQL create action.
func (o *geoEntityCreate) sqlCreate(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.createSpec()
		res       = o.es
		cursor    = 0
	)
	if err != nil {
		return err
	}
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := res[cursor]
		cursor++
		args := e.scan(fields)
		if err := rows.Scan(args...); err != nil {
			return err
		} else {
			res = append(res, e)
			return e.setUnchanged()
		}
	}
	return entitysql.NewCreate(ctx, tx, spec)
}

// createSpec creates the create action spec. It checks for required fields and sets the returning fields.
func (o *geoEntityCreate) createSpec() (*entitysql.CreateSpec, error) {
	returning := []entitysql.FieldName{
		geo_demo.FieldID.Name,
	}
	entity := geo_demo.Entity
	columns := geo_demo.Columns
	spec := entitysql.NewCreateSpec(entity, columns)
	spec.Fields = make([][]*entitysql.FieldSpec, 0, len(o.es))
	for _, e := range o.es {
		fields := make([]*entitysql.FieldSpec, 0, len(geo_demo.Columns))
		for j := range geo_demo.Columns {
			switch geo_demo.Columns[j] {
			case geo_demo.FieldPoint.Name:
				v, err := e.Point.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPoint.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Point.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldLineString.Name:
				v, err := e.LineString.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldLineString.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.LineString.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldPolygon.Name:
				v, err := e.Polygon.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPolygon.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.Polygon.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldMultiPoint.Name:
				v, err := e.MultiPoint.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPoint.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.MultiPoint.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldMultiLineString.Name:
				v, err := e.MultiLineString.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiLineString.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.MultiLineString.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldMultiPolygon.Name:
				v, err := e.MultiPolygon.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPolygon.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.MultiPolygon.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldCircularString.Name:
				v, err := e.CircularString.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldCircularString.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.CircularString.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldPointJson.Name:
				v, err := e.PointJson.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPointJson.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.PointJson.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldLineStringJson.Name:
				v, err := e.LineStringJson.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldLineStringJson.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.LineStringJson.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldPolygonJson.Name:
				v, err := e.PolygonJson.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPolygonJson.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.PolygonJson.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldMultiPointJson.Name:
				v, err := e.MultiPointJson.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPointJson.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.MultiPointJson.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldMultiLineStringJson.Name:
				v, err := e.MultiLineStringJson.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiLineStringJson.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.MultiLineStringJson.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			case geo_demo.FieldMultiPolygonJson.Name:
				v, err := e.MultiPolygonJson.SqlParam(o.config.Driver.Dialect())
				if err != nil {
					return nil, err
				}
				fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPolygonJson.Name)
				fieldSpace.Param = v
				fieldSpace.ParamFormat = e.MultiPolygonJson.SqlFormatParam()
				fields = append(fields, &fieldSpace)
			}
		}
		spec.Fields = append(spec.Fields, fields)
	}
	spec.Returning = returning
	return spec, nil
}
