// Code generated by taurus_go/entity, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/geo_demo"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

// geoEntityQuery is the query action for the geoEntity.
type geoEntityQuery struct {
	config       *geoEntityConfig
	ctx          *entitysql.QueryContext
	predicates   []entitysql.PredicateFunc
	rels         []geoEntityRel
	order        []geo_demo.OrderTerm
	scanner      []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *geoEntityQuery) First(ctx context.Context) (*GeoEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// newGeoEntityQuery creates a new geoEntityQuery.
func newGeoEntityQuery(c *internal.Dialect, t entity.Tracker, ms *geoEntityMutations) *geoEntityQuery {
	return &geoEntityQuery{
		config: &geoEntityConfig{
			Dialect:            c,
			geoEntityMutations: ms,
		},
		ctx:          &entitysql.QueryContext{},
		predicates:   []entitysql.PredicateFunc{},
		rels:         []geoEntityRel{},
		order:        []geo_demo.OrderTerm{},
		scanner:      []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}

func (o *geoEntityQuery) Where(predicates ...entitysql.PredicateFunc) *geoEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *geoEntityQuery) Limit(limit int) *geoEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (o *geoEntityQuery) Order(term ...geo_demo.OrderTerm) *geoEntityQuery {
	o.order = append(o.order, term...)
	return o
}

func (o *geoEntityQuery) Include(rels ...geoEntityRel) *geoEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *geoEntityQuery) ToList(ctx context.Context) ([]*GeoEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *geoEntityQuery) Single(ctx context.Context) (*GeoEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *geoEntityQuery) sqlSingle(ctx context.Context) (*GeoEntity, error) {
	var (
		spec = o.querySpec()
		res  *GeoEntity
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *GeoEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan(fields)...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}
			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = e
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	if res != nil {
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		r.reset()
	}
	return res, nil
}

func (o *geoEntityQuery) sqlAll(ctx context.Context) ([]*GeoEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*GeoEntity{}
	)
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *GeoEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0, e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergeGeoEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *geoEntityQuery) querySpec() *entitysql.QuerySpec {
	s := entitysql.NewQuerySpec(geo_demo.Entity, geo_demo.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s = entitysql.NewQuerySpec(geo_demo.Entity, fields)
	}
	for i := range s.Entity.Columns {
		switch geo_demo.Columns[i] {
		case geo_demo.FieldID.Name:
			var a *geoDemoID = new(geoDemoID)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldID.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldPoint.Name:
			var a *geoDemoPoint = new(geoDemoPoint)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPoint.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldLineString.Name:
			var a *geoDemoLineString = new(geoDemoLineString)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldLineString.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldPolygon.Name:
			var a *geoDemoPolygon = new(geoDemoPolygon)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPolygon.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldMultiPoint.Name:
			var a *geoDemoMultiPoint = new(geoDemoMultiPoint)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPoint.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldMultiLineString.Name:
			var a *geoDemoMultiLineString = new(geoDemoMultiLineString)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiLineString.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldMultiPolygon.Name:
			var a *geoDemoMultiPolygon = new(geoDemoMultiPolygon)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPolygon.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldCircularString.Name:
			var a *geoDemoCircularString = new(geoDemoCircularString)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldCircularString.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldPointJson.Name:
			var a *geoDemoPointJson = new(geoDemoPointJson)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPointJson.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldLineStringJson.Name:
			var a *geoDemoLineStringJson = new(geoDemoLineStringJson)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldLineStringJson.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldPolygonJson.Name:
			var a *geoDemoPolygonJson = new(geoDemoPolygonJson)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldPolygonJson.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldMultiPointJson.Name:
			var a *geoDemoMultiPointJson = new(geoDemoMultiPointJson)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPointJson.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldMultiLineStringJson.Name:
			var a *geoDemoMultiLineStringJson = new(geoDemoMultiLineStringJson)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiLineStringJson.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		case geo_demo.FieldMultiPolygonJson.Name:
			var a *geoDemoMultiPolygonJson = new(geoDemoMultiPolygonJson)
			fieldSpace := entitysql.NewFieldSpec(geo_demo.FieldMultiPolygonJson.Name)
			fieldSpace.NameFormat = a.SqlSelectFormat()
			s.Entity.Columns[i] = fieldSpace
		}
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps {
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, geo_demo.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func(s *entitysql.Selector) {
				o.scanner = o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func(order *entitysql.Order) {
			o.Apply(order)
		})
	}
	return s
}

func (o *geoEntityQuery) addRels(s *entitysql.Selector, t *entitysql.SelectTable, rel rel, scanner []*internal.QueryScanner) []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tableNum := join.GetAs()
	qs := internal.QueryScanner{Config: config, Children: []*internal.QueryScanner{}, TableNum: tableNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}
