// Code generated by taurus_go, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/internal"
	"taurus_go_demo/entity/new/entity/post"

	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
)

// PostEntityCreate is the create action for the PostEntity.
type PostEntityCreate struct {
	config *internal.Dialect
	es     []*PostEntity
}

// NewPostEntityCreate creates a new PostEntityCreate.
func NewPostEntityCreate(c *internal.Dialect, es ...*PostEntity) *PostEntityCreate {
	return &PostEntityCreate{
		config: c,
		es:     es,
	}
}

// create executes the create action.
func (o *PostEntityCreate) create(ctx context.Context, tx dialect.Tx) error {
	return o.sqlCreate(ctx, tx)
}

// sqlCreate executes the SQL create action.
func (o *PostEntityCreate) sqlCreate(ctx context.Context, tx dialect.Tx) error {
	var (
		spec, err = o.createSpec()
		res       = o.es
		cursor    = 0
	)
	if err != nil {
		return err
	}
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := res[cursor]
		cursor++
		args := e.scan(fields)
		if err := rows.Scan(args...); err != nil {
			return err
		} else {
			res = append(res, e)
			return e.setUnchanged()
		}
	}
	return entitysql.NewCreate(ctx, tx, spec)
}

// createSpec creates the create action spec. It checks for required fields and sets the returning fields.
func (o *PostEntityCreate) createSpec() (*entitysql.CreateSpec, error) {
	returning := []entitysql.FieldName{
		post.FieldID.Name,
	}
	entity := post.Entity
	columns := post.Columns
	spec := entitysql.NewCreateSpec(entity, columns)
	spec.Fields = make([][]*entitysql.FieldSpec, 0, len(o.es))
	for _, e := range o.es {
		fields := make([]*entitysql.FieldSpec, 0, len(post.Columns))
		for j := range post.Columns {
			switch post.Columns[j] {
			case post.FieldContent.Name:
				if err := spec.CheckRequired(post.FieldContent.Name, e.Content); err != nil {
					return nil, err
				}
				fields = append(fields, &entitysql.FieldSpec{
					Column: post.FieldContent.Name.String(),
					Value:  e.Content.Value(),
				})
			case post.FieldBlogID.Name:
				if err := spec.CheckRequired(post.FieldBlogID.Name, e.BlogID); err != nil {
					return nil, err
				}
				fields = append(fields, &entitysql.FieldSpec{
					Column: post.FieldBlogID.Name.String(),
					Value:  e.BlogID.Value(),
				})
			case post.FieldAuthorID.Name:
				if err := spec.CheckRequired(post.FieldAuthorID.Name, e.AuthorID); err != nil {
					return nil, err
				}
				fields = append(fields, &entitysql.FieldSpec{
					Column: post.FieldAuthorID.Name.String(),
					Value:  e.AuthorID.Value(),
				})
			}
		}
		spec.Fields = append(spec.Fields, fields)
	}
	spec.Returning = returning
	return spec, nil
}
