// Code generated by taurus_go, DO NOT EDIT.

package entity

import (
	"context"
	"taurus_go_demo/entity/new/entity/internal"

	"github.com/yohobala/taurus_go/entity"
	"github.com/yohobala/taurus_go/entity/dialect"
	"github.com/yohobala/taurus_go/entity/entitysql"
	"github.com/yohobala/taurus_go/tlog"

	"taurus_go_demo/entity/new/entity/post"
)

// PostEntityQuery is the query action for the PostEntity.
type PostEntityQuery struct {
	config     *PostEntityConfig
	ctx        *entitysql.QueryContext
	predicates []func(*entitysql.Predicate)
	rels      []PostEntityRel
	order      []post.OrderTerm
	scanner    []*internal.QueryScanner
	scannerTotal int
}

// First returns the first result of the query.
func (o *PostEntityQuery) First(ctx context.Context) (*PostEntity, error) {
	result, err := o.Single(ctx)
	if err != nil {
		return nil, err
	}
	return result, nil
}

// NewPostEntityQuery creates a new PostEntityQuery.
func NewPostEntityQuery(c *internal.Dialect, t entity.Tracker, ms *postMutations) *PostEntityQuery {
	return &PostEntityQuery{
		config: &PostEntityConfig{
			Dialect:    c,
			postMutations: ms,
		},
		ctx: &entitysql.QueryContext{},
		predicates: []func(*entitysql.Predicate){},
		rels: []PostEntityRel{},
		order: []post.OrderTerm{},
		scanner: []*internal.QueryScanner{},
		scannerTotal: 0,
	}
}


func (o *PostEntityQuery) Where(predicates ...func(*entitysql.Predicate)) *PostEntityQuery {
	o.predicates = append(o.predicates, predicates...)
	return o
}

// Limit sets the limit of the query.
func (o *PostEntityQuery) Limit(limit int) *PostEntityQuery {
	o.ctx.Limit = &limit
	return o
}

func (pq *PostEntityQuery) Order(o ...post.OrderTerm) *PostEntityQuery {
	pq.order = append(pq.order, o...)
	return pq
}

func (o *PostEntityQuery) Include(rels ...PostEntityRel) *PostEntityQuery {
	o.rels = append(o.rels, rels...)
	return o
}

// ToList returns the list of results of the query.
func (o *PostEntityQuery) ToList(ctx context.Context) ([]*PostEntity, error) {
	return o.sqlAll(ctx)
}

// Single returns the single result of the query.
func (o *PostEntityQuery) Single(ctx context.Context) (*PostEntity, error) {
	limit := 1
	o.ctx.Limit = &limit
	return o.sqlSingle(ctx)
}

func (o *PostEntityQuery) sqlSingle(ctx context.Context) (*PostEntity, error) {
	var (
		spec = o.querySpec()
		res  = o.config.New()
	)
	switch res := res.(type) {
	case *PostEntity:
		spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
			builder := entitysql.NewScannerBuilder(o.scannerTotal)
			builder.Append(0,res.scan(fields)...)
			for _, s := range o.scanner {
				res.createRel(builder, s)
			}

			return rows.Scan(builder.Flatten()...)
		}
		if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
			return nil, err
		}
		if err := res.setUnchanged(); err != nil {
			return nil, err
		}
		for _, r := range o.rels {
			r.reset()
		}
		return res, nil
	default:
		return nil, entity.Err_0100030006
	}
	
}

func (o *PostEntityQuery) sqlAll(ctx context.Context) ([]*PostEntity, error) {
	var (
		spec = o.querySpec()
		res  = []*PostEntity{}
	)
	tlog.Print(len(spec.Rels))
	spec.Scan = func(rows dialect.Rows, fields []entitysql.ScannerField) error {
		e := o.config.New()
		switch e := e.(type) {
		case *PostEntity:
			builder := entitysql.NewScannerBuilder(o.scannerTotal + 1)
			builder.Append(0,e.scan([]entitysql.ScannerField{})...)
			for _, s := range o.scanner {
				e.createRel(builder, s)
			}

			if err := rows.Scan(builder.Flatten()...); err != nil {
				return err
			} else {
				res = mergePostEntity(res, e)
				return nil
			}
		default:
			return entity.Err_0100030006
		}
	}
	if err := entitysql.NewQuery(ctx, o.config.Driver, spec); err != nil {
		return nil, err
	}
	for _, e := range res {
		if err := e.setUnchanged(); err != nil {
			return nil, err
		}
	}
	for _, r := range o.rels {
		rel := r
		rel.reset()
	}
	return res, nil
}

func (o *PostEntityQuery) querySpec() *entitysql.QuerySpec {
	tlog.Print(len(o.rels))
	s := entitysql.NewQuerySpec(post.Entity, post.Columns)
	if o.ctx.Limit != nil {
		s.Limit = *o.ctx.Limit
	}
	if fields := o.ctx.Fields; len(fields) > 0 {
		s.Entity.Columns = make([]entitysql.FieldName, 0, len(fields))
		s.Entity.Columns = append(s.Entity.Columns, fields...)
	}
	if ps := o.predicates; len(ps) > 0 {
		s.Predicate = func(p *entitysql.Predicate) {
			for _, f := range ps { 
				f(p)
			}
		}
	}
	if rs := o.rels; len(rs) > 0 {
		s.Rels = make([]entitysql.Relation, 0, len(rs))
		s.Orders = append(s.Orders, post.ByPrimary)
		for _, r := range rs {
			rel := r
			s.Rels = append(s.Rels, func (s *entitysql.Selector)  {
				o.scanner =  o.addRels(s, s.Table(), rel, o.scanner)
			})
		}
	}
	for _, o := range o.order {
		s.Orders = append(s.Orders, func (order *entitysql.Order)  {
			o.Apply(order)
		})
	}
	
	return s
}
func (o *PostEntityQuery) addRels(s *entitysql.Selector,t *entitysql.SelectTable, rel Rel, scanner []*internal.QueryScanner)  []*internal.QueryScanner {
	desc, children, config := rel.Desc()
	join := entitysql.AddRelBySelector(s, t, desc)
	_, tbaleNum := join.GetAs()
	qs := internal.QueryScanner{Config: config,Children: []*internal.QueryScanner{}, TableNum: tbaleNum}
	scanner = append(scanner, &qs)
	o.scannerTotal++
	if len(children) > 0 {
		for _, c := range children {
			qs.Children = o.addRels(s, join, c, qs.Children)
		}
	}
	return scanner
}