// Code generated by taurus_go/entity, DO NOT EDIT.

package geo_demo

import (
	"github.com/yohobala/taurus_go/entity/entitysql"
)

const (
	Entity = "geo_demo"
)

var (
	FieldID = entitysql.Field{
		Name:     "id",
		Primary:  1,
		Default:  true,
		Required: true,
	}
	FieldPoint = entitysql.Field{
		Name:     "point",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldLineString = entitysql.Field{
		Name:     "line_string",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldPolygon = entitysql.Field{
		Name:     "polygon",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldMultiPoint = entitysql.Field{
		Name:     "multi_point",
		Primary:  0,
		Default:  false,
		Required: false,
	}
	FieldMultiLineString = entitysql.Field{
		Name:     "multi_line_string",
		Primary:  0,
		Default:  false,
		Required: false,
	}
	FieldMultiPolygon = entitysql.Field{
		Name:     "multi_polygon",
		Primary:  0,
		Default:  false,
		Required: false,
	}
	FieldCircularString = entitysql.Field{
		Name:     "circular_string",
		Primary:  0,
		Default:  false,
		Required: false,
	}
)

var (
	Columns = []entitysql.FieldName{
		FieldID.Name,
		FieldPoint.Name,
		FieldLineString.Name,
		FieldPolygon.Name,
		FieldMultiPoint.Name,
		FieldMultiLineString.Name,
		FieldMultiPolygon.Name,
		FieldCircularString.Name,
	}
)
