// Code generated by taurus_go/entity, DO NOT EDIT.

package geo_demo

import (
	"github.com/zodileap/taurus_go/datautil/geo"
	"github.com/zodileap/taurus_go/entity/entitysql"
)

type PredID struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredID) EQ(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredID) NEQ(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredID) GT(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredID) GTE(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredID) LT(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredID) LTE(id int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredID) In(ids ...int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		p.In(FieldID.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredID) NotIn(ids ...int64) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		p.NotIn(FieldID.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredID) Like(id string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldID.Name.String(), p.Builder.FindAs(Entity), id)
	}
}

type PredPoint struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredPoint) EQ(point *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredPoint) NEQ(point *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredPoint) GT(point *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredPoint) GTE(point *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredPoint) LT(point *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredPoint) LTE(point *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredPoint) In(points ...*geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(points))
		for i := range v {
			v[i] = points[i]
		}
		p.In(FieldPoint.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredPoint) NotIn(points ...*geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(points))
		for i := range v {
			v[i] = points[i]
		}
		p.NotIn(FieldPoint.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredPoint) Like(point string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldPoint.Name.String(), p.Builder.FindAs(Entity), point)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredPoint) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldPoint.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredPoint) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldPoint.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredLineString struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredLineString) EQ(line_string *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredLineString) NEQ(line_string *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredLineString) GT(line_string *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredLineString) GTE(line_string *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredLineString) LT(line_string *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredLineString) LTE(line_string *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredLineString) In(line_strings ...*geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(line_strings))
		for i := range v {
			v[i] = line_strings[i]
		}
		p.In(FieldLineString.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredLineString) NotIn(line_strings ...*geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(line_strings))
		for i := range v {
			v[i] = line_strings[i]
		}
		p.NotIn(FieldLineString.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredLineString) Like(line_string string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldLineString.Name.String(), p.Builder.FindAs(Entity), line_string)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredLineString) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldLineString.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredLineString) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldLineString.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredPolygon struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredPolygon) EQ(polygon *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredPolygon) NEQ(polygon *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredPolygon) GT(polygon *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredPolygon) GTE(polygon *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredPolygon) LT(polygon *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredPolygon) LTE(polygon *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredPolygon) In(polygons ...*geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(polygons))
		for i := range v {
			v[i] = polygons[i]
		}
		p.In(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredPolygon) NotIn(polygons ...*geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(polygons))
		for i := range v {
			v[i] = polygons[i]
		}
		p.NotIn(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredPolygon) Like(polygon string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldPolygon.Name.String(), p.Builder.FindAs(Entity), polygon)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredPolygon) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldPolygon.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredPolygon) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldPolygon.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredMultiPoint struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredMultiPoint) EQ(multi_point *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredMultiPoint) NEQ(multi_point *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredMultiPoint) GT(multi_point *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredMultiPoint) GTE(multi_point *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredMultiPoint) LT(multi_point *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredMultiPoint) LTE(multi_point *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredMultiPoint) In(multi_points ...*geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_points))
		for i := range v {
			v[i] = multi_points[i]
		}
		p.In(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredMultiPoint) NotIn(multi_points ...*geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_points))
		for i := range v {
			v[i] = multi_points[i]
		}
		p.NotIn(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredMultiPoint) Like(multi_point string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity), multi_point)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredMultiPoint) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredMultiPoint) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldMultiPoint.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredMultiLineString struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredMultiLineString) EQ(multi_line_string *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredMultiLineString) NEQ(multi_line_string *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredMultiLineString) GT(multi_line_string *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredMultiLineString) GTE(multi_line_string *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredMultiLineString) LT(multi_line_string *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredMultiLineString) LTE(multi_line_string *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredMultiLineString) In(multi_line_strings ...*geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_line_strings))
		for i := range v {
			v[i] = multi_line_strings[i]
		}
		p.In(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredMultiLineString) NotIn(multi_line_strings ...*geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_line_strings))
		for i := range v {
			v[i] = multi_line_strings[i]
		}
		p.NotIn(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredMultiLineString) Like(multi_line_string string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity), multi_line_string)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredMultiLineString) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredMultiLineString) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldMultiLineString.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredMultiPolygon struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredMultiPolygon) EQ(multi_polygon *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredMultiPolygon) NEQ(multi_polygon *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredMultiPolygon) GT(multi_polygon *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredMultiPolygon) GTE(multi_polygon *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredMultiPolygon) LT(multi_polygon *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredMultiPolygon) LTE(multi_polygon *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredMultiPolygon) In(multi_polygons ...*geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_polygons))
		for i := range v {
			v[i] = multi_polygons[i]
		}
		p.In(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredMultiPolygon) NotIn(multi_polygons ...*geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_polygons))
		for i := range v {
			v[i] = multi_polygons[i]
		}
		p.NotIn(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredMultiPolygon) Like(multi_polygon string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity), multi_polygon)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredMultiPolygon) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredMultiPolygon) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldMultiPolygon.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredCircularString struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredCircularString) EQ(circular_string *geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredCircularString) NEQ(circular_string *geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredCircularString) GT(circular_string *geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredCircularString) GTE(circular_string *geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredCircularString) LT(circular_string *geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredCircularString) LTE(circular_string *geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredCircularString) In(circular_strings ...*geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(circular_strings))
		for i := range v {
			v[i] = circular_strings[i]
		}
		p.In(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredCircularString) NotIn(circular_strings ...*geo.CircularString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(circular_strings))
		for i := range v {
			v[i] = circular_strings[i]
		}
		p.NotIn(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredCircularString) Like(circular_string string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldCircularString.Name.String(), p.Builder.FindAs(Entity), circular_string)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredCircularString) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldCircularString.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredCircularString) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldCircularString.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredPointJson struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredPointJson) EQ(point_json *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredPointJson) NEQ(point_json *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredPointJson) GT(point_json *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredPointJson) GTE(point_json *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredPointJson) LT(point_json *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredPointJson) LTE(point_json *geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredPointJson) In(point_jsons ...*geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(point_jsons))
		for i := range v {
			v[i] = point_jsons[i]
		}
		p.In(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredPointJson) NotIn(point_jsons ...*geo.Point) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(point_jsons))
		for i := range v {
			v[i] = point_jsons[i]
		}
		p.NotIn(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredPointJson) Like(point_json string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldPointJson.Name.String(), p.Builder.FindAs(Entity), point_json)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredPointJson) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldPointJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredPointJson) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldPointJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredLineStringJson struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredLineStringJson) EQ(line_string_json *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredLineStringJson) NEQ(line_string_json *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredLineStringJson) GT(line_string_json *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredLineStringJson) GTE(line_string_json *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredLineStringJson) LT(line_string_json *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredLineStringJson) LTE(line_string_json *geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredLineStringJson) In(line_string_jsons ...*geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(line_string_jsons))
		for i := range v {
			v[i] = line_string_jsons[i]
		}
		p.In(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredLineStringJson) NotIn(line_string_jsons ...*geo.LineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(line_string_jsons))
		for i := range v {
			v[i] = line_string_jsons[i]
		}
		p.NotIn(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredLineStringJson) Like(line_string_json string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity), line_string_json)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredLineStringJson) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredLineStringJson) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldLineStringJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredPolygonJson struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredPolygonJson) EQ(polygon_json *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredPolygonJson) NEQ(polygon_json *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredPolygonJson) GT(polygon_json *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredPolygonJson) GTE(polygon_json *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredPolygonJson) LT(polygon_json *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredPolygonJson) LTE(polygon_json *geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredPolygonJson) In(polygon_jsons ...*geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(polygon_jsons))
		for i := range v {
			v[i] = polygon_jsons[i]
		}
		p.In(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredPolygonJson) NotIn(polygon_jsons ...*geo.Polygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(polygon_jsons))
		for i := range v {
			v[i] = polygon_jsons[i]
		}
		p.NotIn(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredPolygonJson) Like(polygon_json string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity), polygon_json)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredPolygonJson) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredPolygonJson) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldPolygonJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredMultiPointJson struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredMultiPointJson) EQ(multi_point_json *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredMultiPointJson) NEQ(multi_point_json *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredMultiPointJson) GT(multi_point_json *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredMultiPointJson) GTE(multi_point_json *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredMultiPointJson) LT(multi_point_json *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredMultiPointJson) LTE(multi_point_json *geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredMultiPointJson) In(multi_point_jsons ...*geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_point_jsons))
		for i := range v {
			v[i] = multi_point_jsons[i]
		}
		p.In(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredMultiPointJson) NotIn(multi_point_jsons ...*geo.MultiPoint) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_point_jsons))
		for i := range v {
			v[i] = multi_point_jsons[i]
		}
		p.NotIn(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredMultiPointJson) Like(multi_point_json string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity), multi_point_json)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredMultiPointJson) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredMultiPointJson) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldMultiPointJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredMultiLineStringJson struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredMultiLineStringJson) EQ(multi_line_string_json *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredMultiLineStringJson) NEQ(multi_line_string_json *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredMultiLineStringJson) GT(multi_line_string_json *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredMultiLineStringJson) GTE(multi_line_string_json *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredMultiLineStringJson) LT(multi_line_string_json *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredMultiLineStringJson) LTE(multi_line_string_json *geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredMultiLineStringJson) In(multi_line_string_jsons ...*geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_line_string_jsons))
		for i := range v {
			v[i] = multi_line_string_jsons[i]
		}
		p.In(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredMultiLineStringJson) NotIn(multi_line_string_jsons ...*geo.MultiLineString) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_line_string_jsons))
		for i := range v {
			v[i] = multi_line_string_jsons[i]
		}
		p.NotIn(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredMultiLineStringJson) Like(multi_line_string_json string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity), multi_line_string_json)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredMultiLineStringJson) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredMultiLineStringJson) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldMultiLineStringJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

type PredMultiPolygonJson struct {
}

// EQ returns a function that sets the predicate to check if the field is equal to the given value.
// Operator "="
func (f *PredMultiPolygonJson) EQ(multi_polygon_json *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.EQ(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// NEQ returns a function that sets the predicate to check if the field is not equal to the given value.
// Operator "<>"
func (f *PredMultiPolygonJson) NEQ(multi_polygon_json *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NEQ(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// GT returns a function that sets the predicate to check if the field is greater than the given value.
// Operator ">"
func (f *PredMultiPolygonJson) GT(multi_polygon_json *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GT(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// GTE returns a function that sets the predicate to check if the field is greater than or equal to the given value.
// Operator ">="
func (f *PredMultiPolygonJson) GTE(multi_polygon_json *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.GTE(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// LT returns a function that sets the predicate to check if the field is less than the given value.
// Operator "<"
func (f *PredMultiPolygonJson) LT(multi_polygon_json *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LT(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// LTE returns a function that sets the predicate to check if the field is less than or equal to the given value.
// Operator "<="
func (f *PredMultiPolygonJson) LTE(multi_polygon_json *geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.LTE(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// In returns a function that sets the predicate to check if the field is in the given values.
// Operator "IN"
func (f *PredMultiPolygonJson) In(multi_polygon_jsons ...*geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_polygon_jsons))
		for i := range v {
			v[i] = multi_polygon_jsons[i]
		}
		p.In(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// NotIn returns a function that sets the predicate to check if the field is not in the given values.
// Operator "NOT IN"
func (f *PredMultiPolygonJson) NotIn(multi_polygon_jsons ...*geo.MultiPolygon) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		v := make([]any, len(multi_polygon_jsons))
		for i := range v {
			v[i] = multi_polygon_jsons[i]
		}
		p.NotIn(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), v...)
	}
}

// Like returns a function that sets the predicate to check if the field is like the given value.
// Operator "LIKE"
func (f *PredMultiPolygonJson) Like(multi_polygon_json string) entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.Like(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity), multi_polygon_json)
	}
}

// IsNull returns a function that sets the predicate to check if the field is null.
// Operator "IS NULL"
func (f *PredMultiPolygonJson) IsNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.IsNull(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity))
	}
}

// NotNull returns a function that sets the predicate to check if the field is not null.
// Operator "IS NOT NULL"
func (f *PredMultiPolygonJson) NotNull() entitysql.PredicateFunc {
	return func(p *entitysql.Predicate) {
		p.NotNull(FieldMultiPolygonJson.Name.String(), p.Builder.FindAs(Entity))
	}
}
