// Code generated by taurus_go/entity, DO NOT EDIT.

package post

import (
	"github.com/zodileap/taurus_go/entity/entitysql"
)

const (
	Entity = "post"
)

var (
	FieldID = entitysql.Field{
		Name:     "id",
		Primary:  1,
		Default:  true,
		Required: true,
	}
	FieldContent = entitysql.Field{
		Name:     "content",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldBlogID = entitysql.Field{
		Name:     "blog_id",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldAuthorID = entitysql.Field{
		Name:     "author_id",
		Primary:  0,
		Default:  false,
		Required: true,
	}
)

var (
	Columns = []entitysql.FieldName{
		FieldID.Name,
		FieldContent.Name,
		FieldBlogID.Name,
		FieldAuthorID.Name,
	}
)
