// Code generated by taurus_go, DO NOT EDIT.

package user

import (
	"github.com/yohobala/taurus_go/entity/entitysql"
)

const (
	Entity = "user"
)

var (
	FieldID = entitysql.Field{
		Name:     "id",
		Primary:  1,
		Default:  true,
		Required: true,
	}
	FieldUUID = entitysql.Field{
		Name:     "uuid",
		Primary:  2,
		Default:  false,
		Required: true,
	}
	FieldName = entitysql.Field{
		Name:     "name",
		Primary:  0,
		Default:  false,
		Required: true,
	}
	FieldEmail = entitysql.Field{
		Name:     "email",
		Primary:  0,
		Default:  false,
		Required: false,
	}
	FieldCreatedTime = entitysql.Field{
		Name:     "created_time",
		Primary:  0,
		Default:  true,
		Required: true,
	}
	FieldDesc = entitysql.Field{
		Name:     "desc",
		Primary:  0,
		Default:  true,
		Required: false,
	}
)

var (
	rows = []entitysql.FieldName{
		FieldID.Name,
		FieldUUID.Name,
		FieldName.Name,
		FieldEmail.Name,
		FieldCreatedTime.Name,
		FieldDesc.Name,
	}
)
